version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare_php
    restart: unless-stopped
    volumes:
      - .:/var/www                # code only
      - vendor-data:/var/www/vendor
      - storage-data:/var/www/storage
    networks:
      - healthcare
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: healthcare_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www:ro             # read-only, prevent overwriting internal config
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - healthcare
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: healthcare_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - healthcare

networks:
  healthcare:

volumes:
  mysql_data:
  vendor-data:
  storage-data:
